FROM atlassian/confluence:8.9.4-ubi9

RUN yum update -y && \
    yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    curl -L -o /etc/yum.repos.d/miktex.repo https://miktex.org/download/fedora/34/miktex.repo && \
    yum install -y miktex poppler-utils && \
    yum clean all